# build an executable named helloworld from helloworld.c
json: all.o 
	$(CC) json-c_1.o -ljson-c -o json-c_1

all.o:
	$(CC) -c json-c_1.c
clean: 
	$(RM) json-c_1 json-c_1.o





# # build an executable named helloworld from helloworld.c
# json: all.o 
# 	$(CC) json.o -ljson-c -o json

# all.o:
# 	$(CC) -c json.c
# clean: 
# 	$(RM) json json.o